import React, { Component } from 'react';

const projects = [
  {
    title: 'Roofstops',
    tagLine: 'Rooftops Worth the Stop',
    format: 'Mobile iOS',
    stack: [ 
      'ReactNative', 
      'Custom API', 
      'Native Maps(Airbnb)',
      'OpenWeatherMaps API',
      'ReactNative Elements',
      'ReactNative Gesture Handler',
      'ReactNative Phone Call',
      'ReactNative Tab View',
      'ReactNative Text Input',
      'ReactNative Vector Icons',
      'React Navigation',
    ],
    info: 'A Mobile app that helps you locate the closest Roof Top bars in your area. By entering your zip code, a list is returned to the user of all the available rooftops, as well as the local temperature. The list is generated by a custom built API and database which was built by our small team. Clicking on a list item will bring the user to a detailed view which includes a picture, the address with a linked map button, the hours of operations(both regular and happy), as well as links to their phone number and website.',
    github: 'https://github.com/Roofstops/Roofstops',
    photos: [],
    objectId: 0,
  },
  {
    title: 'pHOODz',
    tagLine: 'Match with Hott & Available, Food in your Hood',
    format: 'Mobile iOS',
    stack: ['Native iOS Swift 4', 'Xcode 9', 'Firebase', 'GooglePlaces API'],
    info: 'I wanted to make this app as user friendly as possible. To do that, I wrote as much "behind the screen" as I could. Thanks to Apple\'s core functionality kits, and Firebase\'s DB capabilities, user interaction is minimal. 1.) Select or Add a Search Query. 2.) Swipe Left for next choice. 3.) Swipe Right for desired choice. 4.) Navigate to destination.',
    github: 'https://github.com/giblerw/pHOODz',
    photos: [],
    objectId: 1,
  },
  {
    title: '',
    tagLine: '',
    format: '',
    stack: [],
    info: '',
    github: '',
    photos: [],
    objectId: 2,
  },
  {
    title: '',
    tagLine: '',
    format: '',
    stack: [],
    info: '',
    github: '',
    photos: [],
    objectId: 3,
  },
];

class Projects extends Component {
  render() {
    return(
      <div className="projects_content">
      <span className="row section_header projects_header"><u>Projects</u></span>
      {projects.map(project => {
        return (
          <div className="row project_row" key={project.objectId}>
            <div className="col-md-4 project-left">walkthrough</div>
            <div className="container col-md-8 project-center">
              <h2 className="row app_title">{project.title}</h2>
              <p className="app_subtitle">"{project.tagLine}"</p>
              <div className="row project_content_row">
                <div className="col-md-3 project_content-left">Left</div>
                <div className="col-md-3 project_content-center">Center</div>
                <div className="col-md-6 project_content-right">Right</div>
              </div>
            </div>
          </div>
        )
      })
      }
      </div>
    )
  }
}

export default Projects;
